import type {Metadata} from "next";
import {PageHero,ArticleNav,Sections,References,Documents,Figures,type Section} from "@/components/ResearchPage";
import {asset} from "@/lib/site";
export const metadata:Metadata={title:"Professor AbulKalam M. Shamsuddin",description:"The scientific biography of AbulKalam M. Shamsuddin, whose IP6 and inositol experiments began at the University of Maryland School of Medicine in 1985."};
const sections:Section[]=[
{id:"career",title:"A career in pathology and discovery",paragraphs:["AbulKalam M. Shamsuddin, M.B., B.S., PhD, graduated from the University of Dhaka’s Dhaka Medical College. He completed an internship in Massachusetts and pathology residency training in Maryland.","He was certified by the American Board of Pathology in 1977 and joined the University of Maryland School of Medicine as an instructor that year. He received his PhD from the University of Maryland in 1980 for research on colon carcinogenesis, and became a full professor in 1988.","The original biography describes repeated teaching honors, including the American Medical Students’ Association Golden Apple Award in 1999. Its account of his university appointments and achievements is preserved here as a scientific biography."]},
{id:"ip6",title:"Opening a field of investigation",paragraphs:["Shamsuddin began studying cancer formation and prevention in 1975. In mid-1985, he initiated experiments on the anticancer properties of inositol and IP6, natural constituents of cereals and legumes.","Over the following years, his laboratory investigated the compounds in different experimental cancer models. He helped organize the First International Symposium of Disease Prevention by IP6 and Other Rice Components in Kyoto, Japan, on June 8–9, 1998.","This history connects his work in pathology with a broader program of research on naturally occurring molecules, cellular behavior, and the possibilities of disease prevention."]},
{id:"screening",title:"Cancer markers and early detection",paragraphs:["His work on the steps of colon carcinogenesis led to research on screening tests intended to identify cancer-associated changes and precancerous lesions. The original biography describes investigations of the Gal-GalNAc marker and the associated field-effect phenomenon.","This research extended to markers studied in lung and breast cancer, with additional proposed applications in prostate and cervical cancer. The source biography reports use of a colon screening approach in China from the early 1990s. These are historical research descriptions; they do not identify a current recommended screening pathway.","His book Diagnostic Assays for Colon Cancer, published by CRC Press in 1991, was written for healthcare professionals. Original screening-related documents are available below."],refs:["7812349","8033605","7805025","8762480","15197795"]},
{id:"education",title:"Sharing the science",paragraphs:["The original biography reports more than 200 scientific publications across Shamsuddin’s career, as well as contributions to book chapters. That count describes his broader publication record, not a count of clinical trials or IP6 studies.","His books include IP6 + Inositol: Nature’s Medicine for the Millennium. The source also notes an earlier book available in Japanese. In 2015, he and Guang-Yu Yang edited Inositol & its Phosphates: Basic Science to Practical Applications, connecting multiple fields of investigation."]},
{id:"service",title:"Service beyond the laboratory",paragraphs:["A veteran of the Bangladesh Liberation War, Shamsuddin was the founding president of the IP-6 Foundation, Inc. in Baltimore and Komolpur Janakallyan Trust in Dhaka.","The original biography describes these nonprofit organizations as supporting healthcare and economic empowerment in rural Bangladesh. It also references his personal writing about the Bangladesh Liberation War."]}
];
export default function Scientist(){return <><PageHero dark eyebrow="Our scientist" title="AbulKalam M. Shamsuddin" description="M.B., B.S., PhD. A scientific career spanning pathology, cancer biology, and the investigation of IP6 and inositol."/><div className="wrap article-layout"><ArticleNav sections={sections} extra={[["milestones","Career milestones"],["documents","Original documents"]]}/><div><div className="portrait-block"><img src={asset("/source/119434971.jpg")} alt="Professor AbulKalam M. Shamsuddin"/><div><p className="eyebrow">The origins of the research</p><h2>A question that became a lifelong pursuit.</h2><p>From colon carcinogenesis to the biology of inositol phosphates, his work connects an interest in early disease processes with the search for new scientific understanding.</p></div></div><Sections sections={sections}/><section className="article-section" id="milestones"><h2>Career milestones</h2><div className="timeline">{[
["1975","Began research on cancer formation and prevention."],["1977","Joined the University of Maryland School of Medicine faculty."],["1980","Received a PhD for research on colon carcinogenesis."],["1985","Began experiments on IP6 and inositol."],["1988","Became a full professor of pathology."],["1998","Helped organize the international IP6 symposium in Kyoto."],["1999","Received the Golden Apple teaching award."],["2015","Co-edited Inositol & its Phosphates."]
].map(([year,text])=><div className="timeline-row" key={year}><strong>{year}</strong><p>{text}</p></div>)}</div></section><section className="article-section" id="documents"><h2>Original screening research documents</h2><Documents items={[["78668836.pdf","Colon screening research","Document linked in the original biography"],["78668832.pdf","Cancer marker research","Document linked in the original biography"]]}/></section><Figures items={[["42362113_scaled_259x400.jpg","Book cover linked in the original scientific biography."]]}/><References source="the-scientist.html"/></div></div></>}