import Link from "next/link";
import HeroMolecule from "@/components/HeroMolecule";
import {ArrowRight,ArrowUpRight} from "lucide-react";
import {asset} from "@/lib/site";
export default function HomePage(){return <>
<section className="hero"><div className="wrap hero-content"><div className="hero-copy"><p className="eyebrow">IP-6 Research Incorporated</p><h1>Advancing the<br/>science of<br/><span>IP6 + inositol.</span></h1><p className="hero-description">Decades of inquiry into naturally occurring molecules, their biological mechanisms, and their potential in human health.</p><div className="actions"><Link href="/science" className="button">Explore the science <ArrowUpRight size={19}/></Link><Link href="/about" className="text-link">About our research <ArrowRight size={18}/></Link></div></div><figure className="hero-molecule"><HeroMolecule/><figcaption><div><strong>IP6</strong><span>Inositol hexaphosphate · Phytic acid</span></div><span className="chemical-formula">C<sub>6</sub>H<sub>18</sub>O<sub>24</sub>P<sub>6</sub></span></figcaption><div className="atom-key" aria-label="Atom colors"><span><i className="carbon"/>Carbon</span><span><i className="hydrogen"/>Hydrogen</span><span><i className="oxygen"/>Oxygen</span><span><i className="phosphorus"/>Phosphorus</span></div></figure></div></section>
<div className="research-strip"><div className="wrap strip-inner"><strong>A foundation in discovery.</strong><span>Research initiated in 1985</span><span>IP6 + Inositol</span><span>Baltimore, Maryland</span></div></div>
<section className="section"><div className="wrap"><div className="intro-grid"><div><p className="eyebrow">The molecules behind our mission</p><h2>Found in nature.<br/>Understood through science.</h2></div><div className="intro-copy"><p>Inositol and its phosphate derivative IP6 are found in plants and mammalian cells. Their roles in cell signaling, mineral binding, and cellular behavior have inspired decades of scientific investigation.</p><p>IP-6 Research brings that body of work into focus, connecting molecular mechanisms with experimental research and emerging human evidence.</p><Link href="/about" className="text-link">Discover IP-6 Research <ArrowRight size={18}/></Link></div></div><div className="molecule-band"><div className="molecule-picture"><img src={asset("/images/phytic-acid-structure.svg")} alt="Chemical structure of phytic acid with six phosphate groups" width="220" height="220" loading="lazy"/></div><div className="molecule-content"><p className="eyebrow">Meet IP6</p><h3 style={{marginTop:14}}>One molecule. Many avenues of inquiry.</h3><p>Inositol hexaphosphate, also known as phytic acid, consists of an inositol ring with six phosphate groups. That structure is central to its biological interactions.</p><div className="molecule-facts"><span>Inositol hexaphosphate</span><span>IP6 / InsP6</span></div></div></div></div></section>
<section className="section research-section"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">Research focus</p><h2>Following the science.<br/>Across disciplines.</h2></div><p>Investigating the connections between IP6, inositol, and the processes that shape cellular health.</p></div><div className="research-rows">{[
["Cancer biology & immunity","Cell growth, differentiation, and natural killer cell activity in experimental models.","/about#oncology"],
["Cardiovascular & metabolic research","Mineral deposition, platelet function, and glucose metabolism.","/benefits#cardiovascular"],
["Neuroscience & cellular protection","Oxidative stress, neurodegeneration models, and responses to radiation.","/benefits#neuroscience"],
["Molecular mechanisms","Antioxidant chemistry, cell signaling, angiogenesis, and epigenetic regulation.","/science"]
].map(([title,description,href])=><Link href={href} key={title} className="research-row"><h3>{title}</h3><p>{description}</p><ArrowUpRight size={27}/></Link>)}</div><div className="research-foot"><p>These are areas of scientific investigation. The evidence includes laboratory and animal studies, with limited human clinical data.</p><Link href="/benefits" className="text-link">All research areas <ArrowRight size={18}/></Link></div></div></section>
<section className="section"><div className="wrap feature-grid"><div className="scientist-photo"><img src={asset("/source/119434971.jpg")} alt="Professor AbulKalam M. Shamsuddin" width="250" height="320" loading="lazy"/><div className="photo-label"><span>AbulKalam M. Shamsuddin</span><span>M.B., B.S., PhD</span></div></div><div className="feature-copy"><p className="eyebrow">The scientist behind the inquiry</p><h2>The origins of<br/>IP6 research.</h2><p>In 1985, Professor AbulKalam M. Shamsuddin began investigating IP6 and inositol at the University of Maryland School of Medicine. That work opened a sustained exploration of their activity in cancer models and cellular systems.</p><Link href="/scientist" className="text-link">Meet Professor Shamsuddin <ArrowRight size={18}/></Link><p className="credential">Pathology · Cancer prevention research · Scientific education</p></div></div></section>
<section className="section highlights"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">From the research archive</p><h2>Ideas that move inquiry forward.</h2></div><Link href="/news" className="text-link">Explore insights <ArrowRight size={18}/></Link></div><div className="publication-list"><div className="publication-row"><div><span className="tag">Clinical pilot</span></div><div><h3>IP6 + inositol during breast cancer chemotherapy</h3><p>A 2010 randomized pilot study explored quality of life and treatment-related side effects.</p></div><Link href="/news#clinical" className="text-link">Read more <ArrowUpRight size={16}/></Link></div><div className="publication-row"><div><span className="tag">Molecular research</span></div><div><h3>A new family of IP6 citrate compounds</h3><p>The chemistry, proposed applications, and patent history of IP6cit.</p></div><Link href="/news#citrate" className="text-link">Read more <ArrowUpRight size={16}/></Link></div><div className="publication-row"><div><span className="tag">Scientific literature</span></div><div><h3>From basic science to practical applications</h3><p>A multidisciplinary reference on inositol and its phosphates, published in 2015.</p></div><Link href="/news#books" className="text-link">Read more <ArrowUpRight size={16}/></Link></div></div></div></section>
<section className="contact-banner"><div className="wrap"><div><h2>Good science starts with a question.</h2><p>Connect with IP-6 Research about the science of IP6 and inositol.</p></div><Link href="/contact" className="button">Start a conversation <ArrowUpRight size={19}/></Link></div></section>
</>}
