"use client";
import * as Accordion from "@radix-ui/react-accordion";
import {Plus} from "lucide-react";
const msk="https://www.mskcc.org/cancer-care/integrative-medicine/herbs/inositol-hexaphosphate";
const faqs=[
{q:"Does IP6 affect calcium, iron, zinc, or other minerals?",a:["Phytate can bind minerals, and its effects depend on chemical form, diet, dose, and other factors. The original research collection argued against treating every phytate-containing food or preparation as nutritionally harmful, and cited a study involving 412 infants in Guatemala.","That study found no growth benefit from reduced-phytate maize, zinc supplementation, or their combination under its study conditions. It does not establish that phytate never affects mineral absorption. Memorial Sloan Kettering notes that phytic acid may reduce the bioavailability of calcium, iron, magnesium, and zinc. Discuss supplements and mineral intake with your healthcare professional."],links:[["Original infant study","https://pubmed.ncbi.nlm.nih.gov/20335626/"],["Clinical overview",msk]]},
{q:"How should I interpret safety and GRAS references?",a:["The original site points to U.S. food-safety records for inositol and calcium phytate. FDA’s historical Select Committee on GRAS Substances database includes these compounds.","Generally Recognized as Safe relates to specified conditions of food use. It is not approval to treat disease and does not establish the safety of every formulation, dose, or combination with a medicine."],links:[["FDA: calcium phytate","https://hfpappexternal.fda.gov/scripts/fdcc/index.cfm?id=CALCIUMPHYTATE&set=foodsubstances"],["FDA: historical GRAS reviews","https://hfpappexternal.fda.gov/scripts/fdcc/index.cfm?order=ASC&search=&set=SCOGS&showAll=true&sort=Year_of_Report&type=basic"]]},
{q:"Why have researchers combined inositol with IP6?",a:["The original research premise was that adding inositol could influence the pool of lower inositol phosphates, including molecules involved in cellular signaling. Early experiments examined a 1:1 molar combination, as well as the individual compounds.","Researchers compared tumor incidence, number, and volume in animal models, together with natural killer cell activity. Some studies favored the combination, while responses to individual compounds varied by model. These experimental ratios are not dosing instructions for people."],links:[["Experimental combination study","https://pubmed.ncbi.nlm.nih.gov/7767964/"],["Natural killer cell research","https://pubmed.ncbi.nlm.nih.gov/2766453/"]]},
{q:"Where do IP6 and inositol come from?",a:["IP6 occurs naturally in plant seeds, grains, and legumes, as well as mammalian cells. Rice bran and corn are sources described in the original collection for extraction of IP6 and inositol.","The source site also discusses differences between reagent-grade and nutraceutical-grade preparations. Its historical purity figures are preparation-specific, not a specification for products generally. Purity, chemical form, and quality need to be assessed for the actual material being studied."],links:[]},
{q:"Can IP6 or inositol interact with medicines or food?",a:["Interaction questions require attention to the specific compound, formulation, treatment, and person. Laboratory findings of synergy with an anticancer drug do not establish that adding a supplement is safe or effective during treatment.","Memorial Sloan Kettering notes potential mineral-binding interactions and antiplatelet activity that could increase bleeding risk with anticoagulant or antiplatelet drugs, while noting that the clinical relevance is uncertain. Discuss use with your treating team, especially during cancer therapy."],links:[["Clinical interaction information",msk],["Laboratory combination research","https://pubmed.ncbi.nlm.nih.gov/12846414/"]]},
{q:"Where can I find independent assessments of the research?",a:["Start with the original publications and examine the study design, participants or model, formulation, and outcomes. PubMed provides access to abstracts and links to journal articles.","The original site also cited summaries from the American Cancer Society, Memorial Sloan Kettering, and other organizations. Some historical links have changed. Memorial Sloan Kettering’s current overview explains that larger studies are needed to confirm the limited clinical findings."],links:[["Memorial Sloan Kettering",msk],["IP6 literature on PubMed","https://pubmed.ncbi.nlm.nih.gov/?term=inositol+hexaphosphate"]]}
];
export default function FaqAccordion(){return <Accordion.Root type="single" collapsible defaultValue="faq-0">{faqs.map((f,i)=><Accordion.Item key={f.q} value={`faq-${i}`} className="faq-item"><Accordion.Header><Accordion.Trigger className="faq-trigger">{f.q}<Plus size={23}/></Accordion.Trigger></Accordion.Header><Accordion.Content className="faq-answer">{f.a.map(p=><p key={p}>{p}</p>)}{f.links.length>0&&<div className="inline-refs" style={{marginTop:22}}>{f.links.map(([title,href])=><a href={href} key={href} target="_blank" rel="noopener noreferrer">{title} ↗</a>)}</div>}</Accordion.Content></Accordion.Item>)}</Accordion.Root>}